### PR TITLE
Workspace support and better error messages

### LINKED ISSUE #8: Friendly error messages
The error handling could be changed so this doesn't output a Ruby backtrace to the user.

```bash
$ slather coverage -s CGFloatTypeTests/CGFloatType.xcodeproj
/Users/kylef/gems/gems/slather-1.0.1/lib/slather/project.rb:34:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)
	from /Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/simple_output.rb:13:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:50:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:30:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp.rb:6:in `Clamp'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:6:in `<top (required)>'
	from /Users/kylef/gems/bin/slather:23:in `load'
	from /Users/kylef/gems/bin/slather:23:in `<main>'
```

```bash
$ slather
Slathering...
/Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/coveralls.rb:24:in `coveralls_coverage_data': Environment variable `TRAVIS_JOB_ID` not set. Is this running on a travis build? (StandardError)
	from /Users/kylef/gems/gems/slather-1.0.1/lib/slather/coverage_service/coveralls.rb:35:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:50:in `post'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:30:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /Users/kylef/gems/gems/clamp-0.6.3/lib/clamp.rb:6:in `Clamp'
	from /Users/kylef/gems/gems/slather-1.0.1/bin/slather:6:in `<top (required)>'
	from /Users/kylef/gems/bin/slather:23:in `load'
	from /Users/kylef/gems/bin/slather:23:in `<main>'
```

### LINKED ISSUE #175: `profdata_coverage_dir': No coverage directory found. Xcode 7.3
I've been using Slather for awhile with Xcode 7.2.1 with no issues. However after updating to Xcode 7.3 I noticed that coverage data is not accurate. I updated slather to the latest version (2.0.2) and now I'm getting the following error. I tried deleting the DerivedData folder as well. Still no luck

```
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:144:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:310:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:288:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:205:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/command/coverage_command.rb:43:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by ksuther**
* Support for building with Xcode workspaces. Specify `--workspace` or add `workspace` to `.slather.yml` if you run tests in a workspace. This will fix #175 (and is probably the cause of #171, #162, and #154).

* slather errors are printed separately from the exception backtrace, which makes them look a bit less scary. More troubleshooting suggestions are included when there's an error. Fixes #8.

* Added an error if someone specifies a scheme that can't be found (or if it isn't a shared scheme).

* Updated the readme to mention workspaces and to encourage specifying a scheme to get the more accurate coverage detection.

* Fixed code coverage covering the files in `spec` and ignoring the ones `lib` (this means the coverage percentage is going to decrease).

This can be split into multiple pull requests if necessary.

### CODE REVIEW

File: lib/slather/project.rb [hunk 1]
```diff
@@ -61,15 +61,29 @@ def self.open(xcodeproj)
       proj
     end
 
+    def failure_help_string
+      "\n\tAre you sure your project is generating coverage? Try `slather setup your/project.xcodeproj`.\n\tDid you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)\n\tIf you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)"
```
Comment (neonichu) [inline lib/slather/project.rb]: I like this, but I'd rather not have the `setup` command in here, because it is only relevant for folks using older Xcodes.

**Comment by neonichu** [comment]
This PR is great :+1: — thanks a lot, @ksuther! Once comment is addressed and changelog entry is added it is good to merge :)

**Comment by ksuther** [comment]
Done!

**Comment by neonichu** [comment]
:shipit:

**Comment by gblotter** [comment]
@neonichu What is your SOP for tagging and releasing?  Do you wait until you have several things to release?  Or do you tag and release whenever you merge?

**Comment by neonichu** [comment]
@gblotter it depends, if there's PRs lined up that will be finished very soon or just smaller things, I'll tend to wait, more important changes I'm releasing ASAP.

**Comment by gblotter** [comment]
@neonichu Can I ask where this one falls? 😊

**Comment by neonichu** [comment]
Would be the former, but I'm seeing some issues while testing locally, so it might happen later rather than sooner :)

**Comment by ksuther** [comment]
@neonichu Let me know if you run into any regressions from these changes.

**Comment by neonichu** [comment]
@ksuther will do, first have to determine if it is actually one, my projects were using an ancient branch of slather until now

**Comment by lwdupont** [comment]
I am using slather at work, and want to give it a try - easy to pull from master? (still a little new to gems).

**Comment by ksuther** [comment]
@lwdupont `gem build slather.gemspec && gem install slather-2.0.2.gem` will install it locally.

**Comment by lwdupont** [comment]
@ksuther Thanks, and thanks for everyone's work on slather. Seems to work fine with the test shell script I have set up. Still trying to find my cobertura file, but pretty sure that's on me :) (no errors running it). :+1:

**Comment by neonichu** [comment]
@ksuther FYI, I made a small fix in #183 — this was hitting me in my manual testing.
